language: python
python:
  - "3.6"      
  - "3.7"
  - "3.8"
  - "nightly"  
install:
  - pip install antlr4-python3-runtime 
script:
  - python -m unittest opfuzz/tests/runtests.py
  - python opfuzz/tests/integration_tests/opfuzz/sanity_opfuzz.py 
