[package]
name = "cswap"
version = "0.1.0"
authors = ["wolffd <wolffdy0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combine = "4.0.1"
regex = "1.3.6"
nom = "5.1.1"
