[package]
name = "rmutator"
version = "0.1.0"
authors = ["wolffd <wolffdy0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
antlr-rust = "0.1"
itertools = "0.9.0"
rsmt2 = "0.10.0"
